# Generated by Django 6.1 on 2026-08-19 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['org_id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='reconciliation.organization')),
            ],
            options={
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('record_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('category_code', models.CharField(blank=True, max_length=64)),
                ('actor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_a_records', to='reconciliation.location')),
            ],
            options={
                'ordering': ['record_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('entry_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('record_ref', models.CharField(db_index=True, max_length=128)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('raw_value', models.CharField(blank=True, default='', max_length=64)),
                ('parsed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_b_entries', to='reconciliation.location')),
            ],
            options={
                'ordering': ['entry_id'],
            },
        ),
    ]
